app:
  name: wetalk-academy
  host: localhost
  port: 8046
  debug: true
  readTimeout: 10
  writeTimeout: 30
  whitelist:
    - http://localhost:3000
    - http://localhost:5173
    - https://wetalk-ute.vercel.app

database:
  uri:
  name: wetalk_academy
  debug: true

log:
  level:
  filePath:
  maxSizeMB: 10
  console:
  dashboardToken:

server:
  url:

client:
  url:

judge0:
  baseURL:

auth:
  jwtSecret:
