name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.0"
          cache-dependency-path: src/go.sum

      - name: Install dependencies
        working-directory: ./src
        run: go mod download

      - name: Build binary
        working-directory: ./src
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -v -o ../academy-service ./cmd/server
          ls -lh ../academy-service

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-binary
          path: academy-service

  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: app-binary
          path: .

      - name: Prepare remote directory
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            mkdir -p /root/service-go/academy-service

      - name: Upload binary to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          source: "academy-service"
          target: "/root/service-go/academy-service/"

      - name: Set permission & restart service
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            cd /root/service-go/academy-service
            chmod +x academy-service
            systemctl restart academy-service

      - name: Deployment notification
        run: |
          echo "Deployment completed successfully!"
          echo "Environment: Production (VPS)"
          echo "Branch: ${{ github.ref_name }}"
          echo "Commit: ${{ github.sha }}"